"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { getProjectById } from "@/components/project-data";
import {
  PackageEditableSnapshot,
  PackageLineItem,
  VendorPackage,
  buildFinalOutgoingDocumentSnapshot,
  buildPackageEditableSnapshot,
  getAssignmentsForPackage,
  getAssignmentStatusLabel,
  getPackageStatusLabel,
  getVendorStatusClass,
  isPackageDocumentOutdated,
} from "@/components/vendor-data";

type DraftState = PackageEditableSnapshot;

function createEmptyLineItem(): PackageLineItem {
  return {
    id: `line-${Math.random().toString(36).slice(2, 8)}`,
    itemName: "",
    workDetails: "",
    quantity: "1",
    unit: "式",
    note: "",
  };
}

function buildInitialDraft(vendorPackage: VendorPackage): DraftState {
  const project = getProjectById(vendorPackage.projectId);

  return buildPackageEditableSnapshot({
    projectName: vendorPackage.packageProjectInfo.projectNameOverride || project?.name || vendorPackage.projectName,
    clientName: vendorPackage.packageProjectInfo.clientNameOverride || project?.client || "",
    eventDate: vendorPackage.packageProjectInfo.eventDateOverride || project?.eventDate || "",
    loadInTime: vendorPackage.packageProjectInfo.loadInTimeOverride || project?.loadInTime || "",
    location: vendorPackage.packageProjectInfo.locationOverride || project?.location || "",
    lineItems: vendorPackage.outgoingLineItems,
    overallNote: vendorPackage.outgoingOverallNote,
  });
}

function buildDocumentText(vendorName: string, draft: DraftState, generatedAt?: string, generatedBy?: string) {
  return [
    "Final Outgoing Document",
    `Vendor: ${vendorName}`,
    generatedAt ? `Generated At: ${generatedAt}` : null,
    generatedBy ? `Generated By: ${generatedBy}` : null,
    "",
    "[Project Info]",
    `Project Name: ${draft.projectName}`,
    `Client Name: ${draft.clientName}`,
    `Event Date: ${draft.eventDate}`,
    `Load-in Time: ${draft.loadInTime}`,
    `Location: ${draft.location}`,
    "",
    "[Line Items]",
    ...draft.lineItems.flatMap((item, index) => [
      `${index + 1}. ${item.itemName || "(未填寫項目名稱)"}`,
      `   Work Details: ${item.workDetails || "-"}`,
      `   Quantity: ${item.quantity || "-"}`,
      `   Unit: ${item.unit || "-"}`,
      `   Note: ${item.note || "-"}`,
    ]),
    "",
    "[Overall Note]",
    draft.overallNote || "-",
  ]
    .filter(Boolean)
    .join("\n");
}

export function VendorPackageDetail({ vendorPackage }: { vendorPackage: VendorPackage }) {
  const [status, setStatus] = useState(vendorPackage.status);
  const [confirmedAt, setConfirmedAt] = useState(vendorPackage.formallyConfirmedAt);
  const [confirmedBy, setConfirmedBy] = useState(vendorPackage.formallyConfirmedBy);
  const [draft, setDraft] = useState<DraftState>(() => buildInitialDraft(vendorPackage));
  const [savedDraft, setSavedDraft] = useState<DraftState>(() => buildInitialDraft(vendorPackage));
  const [documentSnapshot, setDocumentSnapshot] = useState(vendorPackage.finalOutgoingDocument);
  const [saveFeedback, setSaveFeedback] = useState<string | null>(null);
  const [copyFeedback, setCopyFeedback] = useState<string | null>(null);
  const assignments = useMemo(() => getAssignmentsForPackage(vendorPackage.id), [vendorPackage.id]);
  const hasUnsavedChanges = JSON.stringify(draft) !== JSON.stringify(savedDraft);
  const documentIsOutdated = isPackageDocumentOutdated(savedDraft, documentSnapshot);

  function updateDraft<K extends keyof DraftState>(key: K, value: DraftState[K]) {
    setDraft((current) => ({ ...current, [key]: value }));
  }

  function updateLineItem(id: string, key: keyof PackageLineItem, value: string) {
    setDraft((current) => ({
      ...current,
      lineItems: current.lineItems.map((item) => (item.id === id ? { ...item, [key]: value } : item)),
    }));
  }

  function moveLineItem(id: string, direction: "up" | "down") {
    setDraft((current) => {
      const index = current.lineItems.findIndex((item) => item.id === id);
      if (index === -1) return current;
      const targetIndex = direction === "up" ? index - 1 : index + 1;
      if (targetIndex < 0 || targetIndex >= current.lineItems.length) return current;
      const nextItems = [...current.lineItems];
      [nextItems[index], nextItems[targetIndex]] = [nextItems[targetIndex], nextItems[index]];
      return { ...current, lineItems: nextItems };
    });
  }

  function deleteLineItem(id: string) {
    setDraft((current) => ({
      ...current,
      lineItems: current.lineItems.filter((item) => item.id !== id),
    }));
  }

  function addLineItem() {
    setDraft((current) => ({
      ...current,
      lineItems: [...current.lineItems, createEmptyLineItem()],
    }));
  }

  function handleSave() {
    const nextSavedDraft = buildPackageEditableSnapshot(draft);
    setSavedDraft(nextSavedDraft);
    setSaveFeedback(
      isPackageDocumentOutdated(nextSavedDraft, documentSnapshot)
        ? "已儲存 package 內容，現有發包文件與最新 package snapshot 不一致，需重新生成。"
        : "已儲存 package 內容。",
    );
  }

  function handleGenerateDocument() {
    const isRegenerate = Boolean(documentSnapshot);
    if (isRegenerate) {
      const confirmed = window.confirm("重新生成會覆蓋目前唯一有效的 Final Outgoing Document，確定要繼續嗎？");
      if (!confirmed) {
        return;
      }
    }

    const generatedAt = "2026-04-02 01:20";
    const generatedBy = "CTO Demo User";
    const snapshot = buildPackageEditableSnapshot(savedDraft);

    setDocumentSnapshot(
      buildFinalOutgoingDocumentSnapshot({
        packageId: vendorPackage.id,
        packageCode: vendorPackage.code,
        generatedAt,
        generatedBy,
        snapshot,
      }),
    );
    setSaveFeedback(isRegenerate ? "已重新生成並覆蓋 Final Outgoing Document。" : "已生成 Final Outgoing Document。");
  }

  async function handleCopyDocument() {
    const source = documentSnapshot?.packageSnapshot ?? savedDraft;

    try {
      await navigator.clipboard.writeText(
        buildDocumentText(vendorPackage.vendorName, source, documentSnapshot?.generatedAt, documentSnapshot?.generatedBy),
      );
      setCopyFeedback("文件內容已複製到剪貼簿。");
    } catch {
      setCopyFeedback("瀏覽器無法直接複製，但文件預覽已可手動複製。");
    }
  }

  function handleExportDocument() {
    const source = documentSnapshot?.packageSnapshot ?? savedDraft;

    const blob = new Blob([
      buildDocumentText(vendorPackage.vendorName, source, documentSnapshot?.generatedAt, documentSnapshot?.generatedBy),
    ], {
      type: "text/plain;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${vendorPackage.code}-final-outgoing-document.txt`;
    link.click();
    URL.revokeObjectURL(url);
  }

  function handleFormalConfirm() {
    setStatus("formally_confirmed");
    setConfirmedAt("2026-04-02 01:10");
    setConfirmedBy("Willy");
  }

  const effectiveDocument = documentSnapshot?.packageSnapshot ?? savedDraft;

  return (
    <div className="space-y-6">
      <header className="rounded-3xl border border-blue-200 bg-blue-50/70 p-6 shadow-sm ring-1 ring-blue-100">
        <div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between">
          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-3">
              <span className="inline-flex rounded-full bg-white px-3 py-1 text-xs font-semibold text-blue-700 ring-1 ring-blue-200">Package 編輯台</span>
              <p className="text-sm text-slate-500">{vendorPackage.projectName}</p>
              <span className={`inline-flex rounded-full px-3 py-1 text-xs font-medium ring-1 ${getVendorStatusClass(status)}`}>
                {getPackageStatusLabel(status)}
              </span>
              {hasUnsavedChanges ? (
                <span className="inline-flex rounded-full bg-amber-100 px-3 py-1 text-xs font-medium text-amber-800 ring-1 ring-amber-200">尚有未儲存變更</span>
              ) : null}
            </div>
            <h2 className="mt-3 text-3xl font-semibold tracking-tight text-slate-900">{vendorPackage.title}</h2>
            <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{vendorPackage.summary}</p>
          </div>

          <div className="flex flex-wrap gap-3">
            <button
              onClick={handleSave}
              className="rounded-2xl border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-800 shadow-sm"
            >
              儲存 Package
            </button>
            <button
              onClick={handleGenerateDocument}
              className="rounded-2xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700"
            >
              {documentSnapshot ? "重新生成發包文件" : "生成發包文件"}
            </button>
            <button
              onClick={handleFormalConfirm}
              disabled={status === "formally_confirmed"}
              className="rounded-2xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:bg-slate-300"
            >
              {status === "formally_confirmed" ? "已正式發包" : "確認並正式發包"}
            </button>
          </div>
        </div>
        {saveFeedback ? <p className="mt-4 text-sm font-medium text-blue-800">{saveFeedback}</p> : null}
      </header>

      {documentIsOutdated ? (
        <section className="rounded-3xl border border-amber-200 bg-amber-50 p-5 shadow-sm ring-1 ring-amber-100">
          <p className="text-xs font-semibold tracking-wide text-amber-700">DOCUMENT OUTDATED</p>
          <h3 className="mt-1 text-lg font-semibold text-slate-900">目前發包文件不是最新內容，請重新生成</h3>
          <p className="mt-2 text-sm leading-6 text-slate-600">
            目前是以 package 已儲存 snapshot 與文件內保存的 packageSnapshot 做比對；只要兩者不一致，就代表現有文件已過期。
          </p>
        </section>
      ) : null}

      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-6">
        {[
          ["專案名稱", savedDraft.projectName],
          ["客戶名稱", savedDraft.clientName],
          ["合作廠商", vendorPackage.vendorName],
          ["活動日期", savedDraft.eventDate],
          ["進場時間", savedDraft.loadInTime],
          ["地點", savedDraft.location],
        ].map(([label, value]) => (
          <article key={label} className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200">
            <p className="text-sm text-slate-500">{label}</p>
            <p className="mt-3 text-xl font-semibold tracking-tight text-slate-900">{value}</p>
          </article>
        ))}
      </section>

      <section className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
        <div className="space-y-6">
          <article className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
            <div className="mb-5 flex items-center justify-between gap-3">
              <div>
                <h3 className="text-xl font-semibold text-slate-900">專案資訊（對外文件用）</h3>
                <p className="mt-1 text-sm text-slate-500">預設帶入 project 資料，可在 package 層局部覆寫；不回寫 project 主資料。</p>
              </div>
              <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-700">直接編輯</span>
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              {[
                ["projectName", "專案名稱", draft.projectName],
                ["clientName", "客戶名稱", draft.clientName],
                ["eventDate", "活動日期", draft.eventDate],
                ["loadInTime", "進場時間", draft.loadInTime],
                ["location", "地點", draft.location],
              ].map(([key, label, value]) => (
                <label key={String(key)} className="block">
                  <p className="mb-2 text-sm font-medium text-slate-700">{label}</p>
                  <input
                    value={String(value)}
                    onChange={(event) => updateDraft(key as keyof DraftState, event.target.value as never)}
                    className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none ring-0 transition focus:border-blue-500"
                  />
                </label>
              ))}
            </div>
          </article>

          <article className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
            <div className="mb-5 flex items-center justify-between gap-3">
              <div>
                <h3 className="text-xl font-semibold text-slate-900">最終發包項目明細</h3>
                <p className="mt-1 text-sm text-slate-500">這裡是 Final Outgoing Document 主內容來源，由 package 人工整理，不直接等於 assignment 原文。</p>
              </div>
              <button onClick={addLineItem} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 shadow-sm">
                + 新增明細列
              </button>
            </div>

            <div className="space-y-4">
              {draft.lineItems.map((item, index) => (
                <div key={item.id} className="rounded-3xl border border-slate-200 bg-slate-50 p-4">
                  <div className="mb-4 flex items-center justify-between gap-3">
                    <div className="flex items-center gap-2">
                      <span className="inline-flex rounded-full bg-slate-900 px-2.5 py-1 text-[11px] font-semibold text-white">#{index + 1}</span>
                      <p className="text-sm font-medium text-slate-700">對外明細列</p>
                    </div>
                    <div className="flex flex-wrap gap-2">
                      <button onClick={() => moveLineItem(item.id, "up")} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-medium text-slate-700">上移</button>
                      <button onClick={() => moveLineItem(item.id, "down")} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-medium text-slate-700">下移</button>
                      <button onClick={() => deleteLineItem(item.id)} className="rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-medium text-rose-700">刪除</button>
                    </div>
                  </div>

                  <div className="grid gap-4 md:grid-cols-2">
                    <label className="block md:col-span-2">
                      <p className="mb-2 text-sm font-medium text-slate-700">項目名稱</p>
                      <input value={item.itemName} onChange={(event) => updateLineItem(item.id, "itemName", event.target.value)} className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm" />
                    </label>
                    <label className="block md:col-span-2">
                      <p className="mb-2 text-sm font-medium text-slate-700">工作內容 / 規格說明</p>
                      <textarea value={item.workDetails} onChange={(event) => updateLineItem(item.id, "workDetails", event.target.value)} rows={4} className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm" />
                    </label>
                    <label className="block">
                      <p className="mb-2 text-sm font-medium text-slate-700">數量</p>
                      <input value={item.quantity} onChange={(event) => updateLineItem(item.id, "quantity", event.target.value)} className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm" />
                    </label>
                    <label className="block">
                      <p className="mb-2 text-sm font-medium text-slate-700">單位</p>
                      <input value={item.unit} onChange={(event) => updateLineItem(item.id, "unit", event.target.value)} className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm" />
                    </label>
                    <label className="block md:col-span-2">
                      <p className="mb-2 text-sm font-medium text-slate-700">備註</p>
                      <textarea value={item.note} onChange={(event) => updateLineItem(item.id, "note", event.target.value)} rows={3} className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm" />
                    </label>
                  </div>
                </div>
              ))}
            </div>
          </article>

          <article className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
            <div className="mb-5">
              <h3 className="text-xl font-semibold text-slate-900">文件整體備註</h3>
              <p className="mt-1 text-sm text-slate-500">作為整份文件共用補充說明，由 package 維護。</p>
            </div>
            <textarea
              value={draft.overallNote}
              onChange={(event) => updateDraft("overallNote", event.target.value)}
              rows={5}
              className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm"
            />
          </article>

          <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm ring-1 ring-slate-200">
            <div className="mb-5 flex items-center justify-between gap-3">
              <div>
                <h3 className="text-xl font-semibold text-slate-900">已歸包 Assignments</h3>
                <p className="mt-1 text-sm text-slate-500">來源參考資料區，不直接等於最終發包文件內容。</p>
              </div>
              <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-700">弱化參考區</span>
            </div>
            <div className="space-y-3">
              {assignments.map((assignment, index) => (
                <div key={assignment.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                  <div className="flex items-start justify-between gap-3">
                    <div className="min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="inline-flex rounded-full bg-white px-2.5 py-1 text-[11px] font-semibold text-slate-700 ring-1 ring-slate-200">A{index + 1}</span>
                        <Link href={`/vendor-assignments/${assignment.id}`} className="font-semibold text-slate-900 underline-offset-4 hover:underline">
                          {assignment.title}
                        </Link>
                      </div>
                      <p className="mt-2 text-sm text-slate-500">{assignment.summary}</p>
                      <p className="mt-1 text-sm text-slate-500">規格：{assignment.spec}</p>
                      <p className="mt-1 text-sm text-slate-500">備註：{assignment.note}</p>
                    </div>
                    <span className={`inline-flex rounded-full px-3 py-1 text-xs font-medium ring-1 ${getVendorStatusClass(assignment.status)}`}>
                      {getAssignmentStatusLabel(assignment.status)}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </article>
        </div>

        <div className="space-y-6">
          <article className="rounded-3xl border border-blue-200 bg-white p-6 shadow-sm ring-1 ring-blue-100">
            <div className="mb-5 flex items-start justify-between gap-3">
              <div>
                <h3 className="text-xl font-semibold text-slate-900">Final Outgoing Document</h3>
                <p className="mt-1 text-sm text-slate-500">單一有效文件區：查看、複製、匯出、生成 / 重新生成都在這裡。</p>
              </div>
              <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-700 ring-1 ring-blue-200">single current truth</span>
            </div>

            <div className="flex flex-wrap gap-3">
              <button onClick={handleCopyDocument} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 shadow-sm">複製</button>
              <button onClick={handleExportDocument} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 shadow-sm">匯出</button>
              <button onClick={handleGenerateDocument} className="rounded-2xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white shadow-sm">
                {documentSnapshot ? "重新生成發包文件" : "生成發包文件"}
              </button>
            </div>
            {copyFeedback ? <p className="mt-3 text-sm text-slate-600">{copyFeedback}</p> : null}

            <div className="mt-5 rounded-3xl border border-slate-200 bg-slate-50 p-5">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <p className="text-sm font-medium text-slate-700">目前有效文件</p>
                  <p className="mt-1 text-xs text-slate-500">
                    {documentSnapshot
                      ? `生成時間：${documentSnapshot.generatedAt} / 生成人：${documentSnapshot.generatedBy}`
                      : "尚未生成文件，以下預覽為目前已儲存 package 內容。"}
                  </p>
                  {documentSnapshot ? (
                    <p className="mt-1 text-xs text-slate-500">文件快照：package {documentSnapshot.packageCode} 當下內容</p>
                  ) : null}
                </div>
                {documentIsOutdated ? (
                  <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-medium text-amber-800 ring-1 ring-amber-200">文件已過期</span>
                ) : (
                  <span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-medium text-emerald-800 ring-1 ring-emerald-200">內容最新</span>
                )}
              </div>

              <div className="mt-5 space-y-4 rounded-3xl bg-white p-5 ring-1 ring-slate-200">
                <div className="grid gap-3 text-sm text-slate-700">
                  {[
                    ["專案名稱", effectiveDocument.projectName],
                    ["客戶名稱", effectiveDocument.clientName],
                    ["活動日期", effectiveDocument.eventDate],
                    ["進場時間", effectiveDocument.loadInTime],
                    ["地點", effectiveDocument.location],
                  ].map(([label, value]) => (
                    <div key={String(label)} className="flex items-start justify-between gap-4 border-b border-slate-100 pb-3 last:border-0 last:pb-0">
                      <p className="font-medium text-slate-500">{label}</p>
                      <p className="max-w-[70%] text-right font-medium text-slate-900">{value}</p>
                    </div>
                  ))}
                </div>

                <div>
                  <p className="text-sm font-semibold text-slate-900">發包項目明細</p>
                  <div className="mt-3 space-y-3">
                    {effectiveDocument.lineItems.map((item, index) => (
                      <div key={item.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                        <div className="flex items-start gap-3">
                          <span className="inline-flex rounded-full bg-slate-900 px-2.5 py-1 text-[11px] font-semibold text-white">{index + 1}</span>
                          <div className="min-w-0 flex-1">
                            <p className="font-semibold text-slate-900">{item.itemName || "未填寫項目名稱"}</p>
                            <p className="mt-2 text-sm leading-6 text-slate-700">{item.workDetails || "-"}</p>
                            <div className="mt-3 grid gap-2 text-xs text-slate-500 md:grid-cols-3">
                              <p>數量：{item.quantity || "-"}</p>
                              <p>單位：{item.unit || "-"}</p>
                              <p>備註：{item.note || "-"}</p>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4">
                  <p className="text-sm font-semibold text-slate-900">整體備註</p>
                  <p className="mt-2 text-sm leading-6 text-slate-700">{effectiveDocument.overallNote || "-"}</p>
                </div>
              </div>
            </div>
          </article>

          <article className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
            <div className="mb-5 flex items-center justify-between gap-3">
              <div>
                <h3 className="text-xl font-semibold text-slate-900">Package 補充資訊</h3>
                <p className="mt-1 text-sm text-slate-500">保留既有 package 層資訊與往返摘要。</p>
              </div>
              <span className={`inline-flex rounded-full px-3 py-1 text-xs font-medium ring-1 ${getVendorStatusClass(status)}`}>
                {getPackageStatusLabel(status)}
              </span>
            </div>
            <div className="grid gap-3 md:grid-cols-2">
              {[
                ["Package Code", vendorPackage.code],
                ["交付節奏", vendorPackage.deliveryWindow],
                ["正式發包時間", confirmedAt ?? "尚未正式發包"],
                ["正式發包人", confirmedBy ?? "尚未指定"],
              ].map(([label, value]) => (
                <div key={String(label)} className="rounded-2xl bg-slate-50 p-4">
                  <p className="text-xs font-medium text-slate-500">{label}</p>
                  <p className="mt-2 font-semibold text-slate-900">{value}</p>
                </div>
              ))}
            </div>
            <div className="mt-4 rounded-2xl border border-dashed border-slate-300 bg-white p-4">
              <p className="text-sm text-slate-500">Package Notes</p>
              <p className="mt-2 text-sm leading-6 text-slate-700">{vendorPackage.notes}</p>
            </div>
          </article>
        </div>
      </section>
    </div>
  );
}
